#include<stdio.h>
#include<conio.h>

struct address{
int houseno;
char street[20];
char city[20];
int pincode[6];
};
typedef struct address x;

void main()
{
 int i;
 clrscr();
 x y[5]
 for(i=0,i<=2,i++)
 {
 scanf("%d %s %s %d ",&y[i].houseno,&y[i].street,&y[i].city,&[i].pincode);
 }
 for(i=0,i<=2,i++)
 {
 printf("%d %s %s %d ",&y[i].houseno,&y[i].street,&y[i].city,&[i].pincode);
  }
  getch();
  }



